version: '3.6'
services:
  app-node:
    build: .  
    container_name: app_node_test
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules: